import { useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { ArrowLeft, BrainCircuit, ChevronDown, RefreshCw } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { UnifiedIntelligenceChart } from "@/components/UnifiedIntelligenceChart";

type Range = "1W" | "1M" | "3M" | "6M";
const ranges: Range[] = ["1W", "1M", "3M", "6M"];
const cyan = "#00D4FF";

function fmt(value: number | null | undefined) { return value == null ? "—" : `$${value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function stamp(value: number | null | undefined) { return value ? new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "Unavailable"; }

function Chart({ bars, events, mode }: { bars: Array<{ timestamp:number; open:number; high:number; low:number; close:number; volume:number }>; events: Array<{eventAt:number;type:string;headline:string}>; mode:"candle"|"line" }) {
  const width = 1040, height = 460, priceH = 330, volumeTop = 365;
  const domain = useMemo(() => { const lows=bars.map(b=>b.low), highs=bars.map(b=>b.high); return { min: Math.min(...lows)*.995, max:Math.max(...highs)*1.005 }; }, [bars]);
  if (!bars.length) return <div style={empty}>OHLC HISTORY IS TEMPORARILY UNAVAILABLE.</div>;
  const x=(i:number)=>52+(i/(Math.max(1,bars.length-1)))*930;
  const y=(p:number)=>18+((domain.max-p)/(domain.max-domain.min))*285;
  const maxVol=Math.max(...bars.map(b=>b.volume),1);
  const eventFor=(bar:any)=>events.find(e=>Math.abs(e.eventAt-bar.timestamp)<43_200_000);
  return <UnifiedIntelligenceChart bars={bars} markers={events.map(event=>({ eventAt:event.eventAt, type:event.type, headline:event.headline }))} mode={mode} ariaLabel="Rising Stars price, volume, and verified detection chart"/>;
  /* Legacy rendering retained below temporarily for source comparison.
    {[0,1,2,3,4].map(i=><line key={i} x1="52" x2="982" y1={18+i*71} y2={18+i*71} stroke="rgba(148,163,184,.13)" />)}
    <text x="10" y="18" fill="rgba(180,201,224,.55)" fontSize="11">{fmt(domain.max)}</text><text x="10" y="305" fill="rgba(180,201,224,.55)" fontSize="11">{fmt(domain.min)}</text>
    {mode==="line" ? <polyline fill="none" stroke={cyan} strokeWidth="2.5" points={bars.map((b,i)=>`${x(i)},${y(b.close)}`).join(" ")} /> : bars.map((b,i)=>{const up=b.close>=b.open; const color=up?"#00FF88":"#FF4D6A"; const bw=Math.max(3,700/bars.length); return <g key={b.timestamp}><line x1={x(i)} x2={x(i)} y1={y(b.high)} y2={y(b.low)} stroke={color}/><rect x={x(i)-bw/2} y={y(Math.max(b.open,b.close))} width={bw} height={Math.max(2,Math.abs(y(b.open)-y(b.close)))} fill={color}/></g>})}
    {bars.map((b,i)=><rect key={`v${b.timestamp}`} x={x(i)-Math.max(2,650/bars.length)/2} y={volumeTop+(1-b.volume/maxVol)*56} width={Math.max(2,650/bars.length)} height={(b.volume/maxVol)*56} fill={b.close>=b.open?"rgba(0,255,136,.42)":"rgba(255,77,106,.42)"}/>) }
    <text x="52" y="355" fill="rgba(180,201,224,.5)" fontSize="10">VOLUME · COMPLETED DAILY BARS</text>
    {bars.map((b,i)=>{const event=eventFor(b); return event?<g key={`e${event.type}${b.timestamp}`}><line x1={x(i)} x2={x(i)} y1="10" y2="347" stroke="#FACC15" strokeDasharray="4 4"/><circle cx={x(i)} cy="18" r="7" fill="#FACC15"/><title>{event.headline}</title></g>:null})}
  </svg>; */
}

export default function RisingStarDetail() {
  const [, params] = useRoute<{ ticker: string }>("/app/rising-stars/:ticker");
  const [, navigate] = useLocation(); const [range,setRange]=useState<Range>("3M"); const [mode,setMode]=useState<"candle"|"line">("candle"); const [open,setOpen]=useState(false);
  const ticker=(params?.ticker??"").toUpperCase();
  const query=trpc.outlook.getRisingStarVisualDetail.useQuery({ticker,range},{retry:2,staleTime:60_000}); const d=query.data;
  if(query.isLoading) return <main style={page}><div style={empty}>ASSEMBLING VERIFIED VISUAL ANALYSIS…</div></main>;
  if(query.isError||!d) return <main style={page}><button style={back} onClick={()=>navigate("/app/rising-stars")}>← BACK TO RISING STARS</button><div style={empty}>THIS ASSET IS NOT CURRENTLY AVAILABLE IN THE VERIFIED RISING STARS UNIVERSE.</div></main>;
  const i=d.item, change=i.dailyChangePercent??0, positive=change>=0;
  return <main style={page}><div style={{maxWidth:1380,margin:"0 auto"}}>
    <button style={back} onClick={()=>navigate("/app/rising-stars")}>← BACK TO RISING STARS</button>
    <header style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap",margin:"16px 0"}}><div><div style={{color:cyan,fontSize:10,letterSpacing:".16em"}}>RISING STARS / VISUAL ANALYSIS</div><h1 style={{margin:"5px 0",fontSize:42,fontFamily:"Rajdhani,sans-serif"}}>{i.ticker} <span style={{fontSize:17,color:"#9DAFC1"}}>{i.name}</span></h1><div style={{fontSize:11,color:"#AAB8C8"}}>{i.sector??"SECTOR UNAVAILABLE"} · {i.industry??"INDUSTRY UNAVAILABLE"} · LAST UPDATED {stamp(d.currentContext.marketDataAsOf)}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:34,fontFamily:"Rajdhani,sans-serif",color:positive?"#00FF88":"#FF6B6B"}}>{fmt(i.latestPrice)}</div><div style={{fontSize:11,color:positive?"#00FF88":"#FF6B6B"}}>{positive?"+":""}{change.toFixed(2)}% · {i.priceStatus}</div></div></header>
    <section style={strip}><Stat label="RISING STAR SCORE" value={`${i.risingStarScore}/100`} color={cyan}/><Stat label="SIGNAL" value={`${i.signalDirection} · ${i.signalStrength}`}/><Stat label="MOMENTUM" value={`${i.momentumScore}/100`}/><Stat label="VOLUME" value={`${i.volumeParticipationScore}/100`}/><Stat label="MARKET CONTEXT" value={`${d.currentContext.pressureIndex}/100 · ${d.currentContext.regime}`}/></section>
    <section style={hero}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><b style={{color:"#EAF5FF"}}>PRICE ACTION & VERIFIED SIGNAL EVIDENCE</b><div style={{fontSize:10,color:"#8EA2B8",marginTop:4}}>Yellow markers = immutable LIVE VERIFIED HISTORY only. Price bars do not imply a historical FAULTLINE call.</div></div><div style={{display:"flex",gap:6}}>{ranges.map(r=><button key={r} onClick={()=>setRange(r)} style={chip(range===r)}>{r}</button>)}<button onClick={()=>setMode(mode==="candle"?"line":"candle")} style={chip(false)}>{mode==="candle"?"LINE":"CANDLES"}</button></div></div><div style={{overflowX:"auto",marginTop:12}}><Chart bars={d.bars} events={d.verifiedHistory.events} mode={mode}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:12}}><Metric label="CALCULATED SUPPORT" value={fmt(d.levels.support)}/><Metric label="CALCULATED RESISTANCE" value={fmt(d.levels.resistance)}/><Metric label="HISTORY STATUS" value={d.verifiedHistory.snapshots.length?"LIVE VERIFIED HISTORY":"HISTORY BEGINS WITH FIRST STORED OBSERVATION"}/></div><p style={note}>{d.levels.basis} {d.verifiedHistory.boundaryNote}</p></section>
    <section style={grid}><Panel title="WHY FAULTLINE FLAGGED IT">{i.whySeeingItEarly.map((x:string)=><p key={x} style={copy}>• {x}</p>)}<p style={copy}><b>CATALYST:</b> {i.primaryCatalyst}</p><p style={{...copy,color:"#FACC15"}}><b>KEY RISK:</b> {i.keyRisk}</p></Panel><Panel title="SIGNAL EVOLUTION">{d.verifiedHistory.events.length?<>{d.verifiedHistory.events.map((e:any)=><p key={e.id} style={copy}><b style={{color:"#FACC15"}}>{new Date(e.eventAt).toLocaleDateString()}</b> · {e.headline}</p>)}</>:<p style={copy}>No historical FAULTLINE event markers exist yet. The ledger starts only when a live engine observation is stored.</p>}</Panel></section>
    {d.signalWindow&&<Panel title="SINCE FAULTLINE DETECTION"><div style={metricGrid}><Metric label="DETECTION PRICE" value={fmt(d.signalWindow.detectionPrice)}/><Metric label="CURRENT PRICE" value={fmt(d.signalWindow.currentPrice)}/><Metric label="PRICE MOVEMENT" value={`${d.signalWindow.movementPercent.toFixed(2)}%`}/><Metric label="DAYS ACTIVE" value={`${d.signalWindow.daysActive}`}/></div><p style={note}>{d.signalWindow.note}</p></Panel>}
    <section style={grid}><Panel title="WHAT CHANGED"><p style={copy}>Current score {i.risingStarScore}/100 · momentum {i.momentumScore}/100 · volume participation {i.volumeParticipationScore}/100. Compare future stored observations here as the live record grows.</p></Panel><Panel title="ASK ASHA"><button style={ask} onClick={()=>navigate(`/app/asha?prompt=${encodeURIComponent(`Explain the current ${i.ticker} Rising Star setup, its verified evidence, risk level, and what would invalidate it.`)}`)}><BrainCircuit size={14}/> EXPLAIN THIS CHART</button></Panel></section>
    <section style={panel}><button onClick={()=>setOpen(!open)} style={{...ask,width:"100%",justifyContent:"space-between"}}>SCORE METHODOLOGY <ChevronDown size={15} style={{transform:open?"rotate(180deg)":"none"}}/></button>{open&&<p style={copy}>The canonical score weights completed daily price and volume structure, technical asymmetry, available public-news evidence, and FAULTLINE macro alignment. Missing inputs are excluded, not estimated. It does not forecast returns.</p>}</section>
  </div></main>;
}
function Stat({label,value,color}:{label:string;value:string;color?:string}){return <div><div style={{fontSize:8,color:"#8092A8",letterSpacing:".08em"}}>{label}</div><div style={{fontSize:15,color:color??"#EAF5FF",marginTop:5,fontWeight:700}}>{value}</div></div>}
function Metric({label,value}:{label:string;value:string}){return <div style={{padding:"10px",border:"1px solid rgba(255,255,255,.08)",borderRadius:5}}><div style={{fontSize:8,color:"#8092A8"}}>{label}</div><div style={{fontSize:12,color:"#EAF5FF",marginTop:5}}>{value}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section style={panel}><h2 style={{fontSize:11,color:cyan,letterSpacing:".1em",margin:"0 0 9px"}}>{title}</h2>{children}</section>}
const page:React.CSSProperties={minHeight:"100vh",background:"#050608",color:"#EAF5FF",padding:"22px 16px 90px",fontFamily:"IBM Plex Mono,monospace"}; const hero:React.CSSProperties={border:"1px solid rgba(0,212,255,.24)",background:"rgba(7,10,15,.95)",borderRadius:9,padding:14};const strip:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:10,padding:"13px 15px",border:"1px solid rgba(0,212,255,.18)",borderRadius:7,margin:"0 0 14px",background:"rgba(0,212,255,.04)"};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,340px),1fr))",gap:13,marginTop:13};const panel:React.CSSProperties={border:"1px solid rgba(255,255,255,.09)",background:"rgba(9,13,19,.88)",borderRadius:7,padding:14,marginTop:13};const metricGrid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8};const copy:React.CSSProperties={fontSize:11,lineHeight:1.6,color:"#C3D0DE",margin:"6px 0"};const note:React.CSSProperties={fontSize:9,lineHeight:1.55,color:"#8193A8",margin:"10px 0 0"};const back:React.CSSProperties={border:0,background:"none",color:"#A6B6C7",padding:0,cursor:"pointer",fontSize:10};const ask:React.CSSProperties={border:"1px solid rgba(0,212,255,.28)",background:"rgba(0,212,255,.08)",color:cyan,borderRadius:4,padding:"9px 11px",cursor:"pointer",fontSize:10,display:"inline-flex",alignItems:"center",gap:6};const empty:React.CSSProperties={padding:26,border:"1px solid rgba(0,212,255,.2)",borderRadius:8,color:"#A6B6C7",fontSize:11};const chip=(active:boolean):React.CSSProperties=>({border:"1px solid",borderColor:active?cyan:"rgba(255,255,255,.15)",background:active?"rgba(0,212,255,.13)":"transparent",color:active?"#EAF5FF":"#A6B6C7",borderRadius:4,padding:"7px 9px",cursor:"pointer",fontSize:9});
