import {
  LEGACY_CAPABILITY_AUDIT,
  type CapabilityClassification,
} from "./legacyCapabilityAudit";

export type PageTreatment = "preserve" | CapabilityClassification;

export interface PageTreatmentEntry {
  source: string;
  page: string;
  treatment: PageTreatment;
  destination?: string;
}

/**
 * The authoritative 158-row pre-reorganization page-map scope from the
 * immutable f6106e41 baseline. The six TSX implementation/scaffold modules
 * outside the validated page map are recorded separately below.
 */
export const REORGANIZATION_BASELINE_PAGE_SOURCES = [
  "client/src/pages/About.tsx",
  "client/src/pages/AdminBlog.tsx",
  "client/src/pages/AdminPortal.tsx",
  "client/src/pages/AdminPromoDashboard.tsx",
  "client/src/pages/AdminPublishing.tsx",
  "client/src/pages/AdminUsers.tsx",
  "client/src/pages/AftershockEngine.tsx",
  "client/src/pages/Alerts.tsx",
  "client/src/pages/AltRotation.tsx",
  "client/src/pages/Analysis.tsx",
  "client/src/pages/AnalyticsDashboard.tsx",
  "client/src/pages/AIWatch.tsx",
  "client/src/pages/AshaIntelligenceCenter.tsx",
  "client/src/pages/Blog.tsx",
  "client/src/pages/BlogPost.tsx",
  "client/src/pages/Charts.tsx",
  "client/src/pages/CheckoutSuccess.tsx",
  "client/src/pages/ContactUs.tsx",
  "client/src/pages/CryptoHub.tsx",
  "client/src/pages/CryptoIntelligence.tsx",
  "client/src/pages/CryptoRegimeDashboard.tsx",
  "client/src/pages/CryptoSearch.tsx",
  "client/src/pages/CryptoSignals.tsx",
  "client/src/pages/CryptoWatchlist.tsx",
  "client/src/pages/DailyBriefArchive.tsx",
  "client/src/pages/DailyBriefPost.tsx",
  "client/src/pages/DailyReport.tsx",
  "client/src/pages/Dashboard.tsx",
  "client/src/pages/DayTradeIntelligence.tsx",
  "client/src/pages/DecisionEngine.tsx",
  "client/src/pages/DecisionLedger.tsx",
  "client/src/pages/DiagnosticAI.tsx",
  "client/src/pages/FmosHealthDashboard.tsx",
  "client/src/pages/Glossary.tsx",
  "client/src/pages/Guide.tsx",
  "client/src/pages/HistoricalAnalogs.tsx",
  "client/src/pages/InsiderIntelligence.tsx",
  "client/src/pages/IntelligenceArchive.tsx",
  "client/src/pages/IntelligenceHub.tsx",
  "client/src/pages/IntelligenceLibrary.tsx",
  "client/src/pages/IntelligenceLibraryPost.tsx",
  "client/src/pages/IntelligenceValidation.tsx",
  "client/src/pages/Legal.tsx",
  "client/src/pages/MarketCommandCenter.tsx",
  "client/src/pages/MarketIntelligence.tsx",
  "client/src/pages/MarketMovers.tsx",
  "client/src/pages/MarketingSite.tsx",
  "client/src/pages/Methodology.tsx",
  "client/src/pages/NotFound.tsx",
  "client/src/pages/Opportunities.tsx",
  "client/src/pages/OwnerSimulation.tsx",
  "client/src/pages/PhoenixSystems.tsx",
  "client/src/pages/Portfolio.tsx",
  "client/src/pages/PreFlight.tsx",
  "client/src/pages/Press.tsx",
  "client/src/pages/Pressure.tsx",
  "client/src/pages/PressureIndex.tsx",
  "client/src/pages/PromoRedeem.tsx",
  "client/src/pages/PublicAIBubble.tsx",
  "client/src/pages/PublicAnalogs.tsx",
  "client/src/pages/PublicCryptoMarketRisk.tsx",
  "client/src/pages/PublicCryptoSignals.tsx",
  "client/src/pages/PublicDiagnosticAI.tsx",
  "client/src/pages/PublicSharedReport.tsx",
  "client/src/pages/PublicSignals.tsx",
  "client/src/pages/PublicSituationRoom.tsx",
  "client/src/pages/PublicStockMarketRisk.tsx",
  "client/src/pages/ReadingHistory.tsx",
  "client/src/pages/Roadmap.tsx",
  "client/src/pages/Scenarios.tsx",
  "client/src/pages/Scores.tsx",
  "client/src/pages/SeismographIntelligence.tsx",
  "client/src/pages/SeismographicDash.tsx",
  "client/src/pages/SeoOptimizer.tsx",
  "client/src/pages/SignalOutlookCenter.tsx",
  "client/src/pages/Signals.tsx",
  "client/src/pages/SimPortfolio.tsx",
  "client/src/pages/SimulatePressure.tsx",
  "client/src/pages/SituationRoom.tsx",
  "client/src/pages/SmartDiscovery.tsx",
  "client/src/pages/SocialIntelligence.tsx",
  "client/src/pages/StockHeatmap.tsx",
  "client/src/pages/TodaysStory.tsx",
  "client/src/pages/TrackRecord.tsx",
  "client/src/pages/TradeJournal.tsx",
  "client/src/pages/TradePreflight.tsx",
  "client/src/pages/UniversalSymbolIntelligence.tsx",
  "client/src/pages/UserAccount.tsx",
  "client/src/pages/ValidationLab.tsx",
  "client/src/pages/Watchlist.tsx",
  "client/src/pages/XPostGenerator.tsx",
  "client/src/pages/XPostQueue.tsx",
  "client/src/pages/admin/ChatInbox.tsx",
  "client/src/pages/admin/ConversationIntelligence.tsx",
  "client/src/pages/admin/EngineeringDiagnostics.tsx",
  "client/src/pages/mobile/MobileAccount.tsx",
  "client/src/pages/mobile/MobileBrief.tsx",
  "client/src/pages/mobile/MobileCrypto.tsx",
  "client/src/pages/mobile/MobilePulse.tsx",
  "client/src/pages/mobile/MobileRotation.tsx",
  "client/src/pages/mobile/MobileSignals.tsx",
  "client/src/pages/mobile/MobileUpgrade.tsx",
  "client/src/pages/mobile/MobileWatchlist.tsx",
  "client/src/pages/seo/AAPLSignal.tsx",
  "client/src/pages/seo/AIStockSignals.tsx",
  "client/src/pages/seo/AIStocksDashboard.tsx",
  "client/src/pages/seo/AMDSignal.tsx",
  "client/src/pages/seo/AMZNSignal.tsx",
  "client/src/pages/seo/AltSeasonIndicator.tsx",
  "client/src/pages/seo/BestMarketRiskIndicators.tsx",
  "client/src/pages/seo/BestStockMarketRiskDashboard.tsx",
  "client/src/pages/seo/BitcoinRiskDashboard.tsx",
  "client/src/pages/seo/BitcoinVsStockMarket.tsx",
  "client/src/pages/seo/BullBearConditions.tsx",
  "client/src/pages/seo/BullOrBearMarket.tsx",
  "client/src/pages/seo/CreditMarketStress.tsx",
  "client/src/pages/seo/CryptoBullOrBear.tsx",
  "client/src/pages/seo/CryptoMarketRegime.tsx",
  "client/src/pages/seo/CryptoSignalsIntelligence.tsx",
  "client/src/pages/seo/DIASignal.tsx",
  "client/src/pages/seo/DynamicCryptoPage.tsx",
  "client/src/pages/seo/DynamicStockPage.tsx",
  "client/src/pages/seo/EthereumRiskDashboard.tsx",
  "client/src/pages/seo/FederalReserveTracker.tsx",
  "client/src/pages/seo/IWMSignal.tsx",
  "client/src/pages/seo/IsNowGoodTimeToBuyStocks.tsx",
  "client/src/pages/seo/LiquidityMonitor.tsx",
  "client/src/pages/seo/METASignal.tsx",
  "client/src/pages/seo/MSFTSignal.tsx",
  "client/src/pages/seo/MarketCrashIndicator.tsx",
  "client/src/pages/seo/MarketCrashProbability2026.tsx",
  "client/src/pages/seo/MarketRegimeTracker.tsx",
  "client/src/pages/seo/NVDASignal.tsx",
  "client/src/pages/seo/PLTRSignal.tsx",
  "client/src/pages/seo/QQQSignal.tsx",
  "client/src/pages/seo/RecessionProbability.tsx",
  "client/src/pages/seo/SPYSignal.tsx",
  "client/src/pages/seo/StockMarketRiskToday.tsx",
  "client/src/pages/seo/TAOSignal.tsx",
  "client/src/pages/seo/TSLASignal.tsx",
  "client/src/pages/seo/TreasuryYieldStress.tsx",
  "client/src/pages/seo/VolatilityDashboard.tsx",
  "client/src/pages/seo/learn/LearnBullAndBearMarkets.tsx",
  "client/src/pages/seo/learn/LearnCreditSpreads.tsx",
  "client/src/pages/seo/learn/LearnCryptoCycles.tsx",
  "client/src/pages/seo/learn/LearnFedPolicy.tsx",
  "client/src/pages/seo/learn/LearnHowToReadStockMarket.tsx",
  "client/src/pages/seo/learn/LearnInflationAndStocks.tsx",
  "client/src/pages/seo/learn/LearnMacroInvesting.tsx",
  "client/src/pages/seo/learn/LearnRiskOnRiskOff.tsx",
  "client/src/pages/seo/learn/LearnTreasuryYields.tsx",
  "client/src/pages/seo/learn/LearnWhatCausesMarketCrash.tsx",
  "client/src/pages/seo/learn/LearnWhatIsLiquidity.tsx",
  "client/src/pages/seo/learn/LearnWhatIsMarketRegime.tsx",
  "client/src/pages/seo/vs/VsBloomberg.tsx",
  "client/src/pages/seo/vs/VsFinviz.tsx",
  "client/src/pages/seo/vs/VsKoyfin.tsx",
  "client/src/pages/seo/vs/VsTradingView.tsx",
] as const;

export const NON_ROUTE_PAGE_MODULES = [
  "client/src/pages/ComponentShowcase.tsx",
  "client/src/pages/Home.tsx",
  "client/src/pages/HistoricalContextEngine.tsx",
  "client/src/pages/PublicLandingPage.tsx",
  "client/src/pages/SEOLandingPage.tsx",
  "client/src/pages/seo/StockSignalPage.tsx",
] as const;

const auditByPage = new Map(LEGACY_CAPABILITY_AUDIT.map(entry => [entry.page, entry]));

export const PAGE_TREATMENT_MANIFEST: readonly PageTreatmentEntry[] = REORGANIZATION_BASELINE_PAGE_SOURCES.map(source => {
  const page = source.slice(source.lastIndexOf("/") + 1, -4);
  const audited = auditByPage.get(page);
  return {
    source,
    page,
    treatment: audited?.classification ?? "preserve",
    ...(audited ? { destination: audited.destination } : {}),
  };
});
